### ISSUE TITLE
Can't build error: SDK is not specified for module

### ISSUE THREAD

**Issue by hayesmaker** [4ch1m/kick-assembler-acbg#12]
IntelliJ Idea 2022.1 (Ultimate Edition)

I configured Java JRE and Kickassembler SDK but when I click build or run Intellij bubble pops up saying The SDK is not specified for module.  Also the "BasicUpstart2(start)" in the File template is still colouring in the "sta" in "start" as a different colour. 

run/debug configurations:
![run-config](https://user-images.githubusercontent.com/593429/164496617-43b9b373-8619-478b-bacc-b97d48aeb4a0.PNG)

![project-structure](https://user-images.githubusercontent.com/593429/164497526-f0f945b9-d3d4-4468-bac5-42b2bfbf3921.PNG)

**Comment by jhunnius** [comment]
I have the same issue(s).

**Comment by 4ch1m** [comment]
Running/compiling should work; just tried it with a fresh installation.

Make sure you really have the Java JRE **and** the KickAssember SDK configured properly.

![image](https://user-images.githubusercontent.com/3408832/164884234-8d0dc415-9514-42a0-a825-e630f1651f75.png)

![image](https://user-images.githubusercontent.com/3408832/164884293-4f49dd66-ad8f-4ed8-b669-c91f872f9605.png)

As for the other points; please note the [README](https://github.com/4ch1m/kick-assembler-acbg/blob/master/README.md):

> This plugin is still at an early stage of development. Not all features are fully implemented or work as expected at this point. Feedback, help or any other contributions are very welcome.

Both the [Flex](https://github.com/4ch1m/kick-assembler-acbg/blob/master/app/src/main/java/de/achimonline/kickassembler/acbg/lexer/KickAssembler.flex) and the [BNF](https://github.com/4ch1m/kick-assembler-acbg/blob/master/app/src/main/java/de/achimonline/kickassembler/acbg/psi/KickAssembler.bnf) definitions need major rework/improvements.

Pull-requests or any other help is very welcome!

**Comment by jhunnius** [comment]
Here's a few screenshots:

![image](https://user-images.githubusercontent.com/9149031/165250850-74c94d4c-90b9-4a95-adf3-343035789c82.png)
Is the default JRE a problem?

![image](https://user-images.githubusercontent.com/9149031/165251043-ee6682f1-a717-4254-a79b-1b89e0610d18.png)
The SDK is recognized properly with the default SDK.

![image](https://user-images.githubusercontent.com/9149031/165251236-f61c861f-f320-4e14-b4ea-8d0fabaa3069.png)
Still getting this.

**Comment by jhunnius** [comment]
Same with OpenJDK 18

**Comment by jhunnius** [comment]
Same with OpenJDK 11

**Comment by 4ch1m** [comment]
> ![image](https://user-images.githubusercontent.com/9149031/165250850-74c94d4c-90b9-4a95-adf3-343035789c82.png) Is the default JRE a problem?

What is actually referenced by `11`?
Is the full path to that JRE correct?

**Comment by jhunnius** [comment]
yes, when I pick the path, it only shows the "11". It is the default JRE of both the system and IntelliJ.

It does show the path for the two OpenJDKs

![image](https://user-images.githubusercontent.com/9149031/165376024-ffcc3f7d-062c-498d-9c69-9e2536836070.png)

Same result though, whether I try the /bin path or the root of the JDK. Build won't work.

**Comment by jhunnius** [comment]
Nice website indeed btw. Would you care if I converted it into VIC-20 and C-128 layouts to maybe use them at some point in the future?

**Comment by ic000000n** [comment]
I have the same problem. Could the problem be related to running IntelliJ on Windows?

**Comment by jhunnius** [comment]
My guess is / vs. \ as folder separators, or the drive letter. Something with paths.

**Comment by 4ch1m** [comment]
> My guess is / vs. \ as folder separators, or the drive letter. Something with paths.

It had nothing to do with folder separators, or drive letters. Nothing with paths either.


The plugin-API of IntelliJ seems to have changed regarding module based run-configurations.
Forcing every module to have a configured SDK.

This is now fixed with: 377f265e2498c7a6ff400e322918b21fd8dcc67e

The new plugin version (1.7.0) is currently getting reviewed and should be out soon.
