### ISSUE TITLE
SDK Error

### ISSUE THREAD

**Issue by Siddhesh2377** [4ch1m/kick-assembler-acbg#18]
darkengine@pop-os:~/Downloads/KickAssembler$ java –jar KickAss.jar myCode.asm
Error: Could not find or load main class –jar
Caused by: java.lang.ClassNotFoundException: –jar

**Comment by 4ch1m** [comment]
Sorry. I don't give coding support or tutorials here.

**Comment by Siddhesh2377** [comment]
dude, then what should i do ??
