### ISSUE TITLE
Support for other Jetbrains IDEs like PHPStorm

### ISSUE THREAD

**Issue by lubber-de** [4ch1m/kick-assembler-acbg#2]
## Description
Please adjust your plugin, so it also works in PHPStorm, WebStorm,... as the base IDE is the same.

Your plugin currently cannot be found in the marketplace in those IDEs.
However i am basically able to add the plugin manually and after a restart of PHPStorm the plugin can be found in the plugins list as "installed" but there are no mentioned features available 

- not found unter "Languages" Settings
- "New Project" does not offer "Kickass project"
- Project Settings does not poffer "KickAss JDK"

**Comment by 4ch1m** [comment]
The plugin doesn't explicitly list compatible products (or product IDs).
It simply defines the necessary modules/dependencies.
In this case "Java".

```
    <depends>com.intellij.modules.java</depends>
```

see: [plugin.xml](https://github.com/4ch1m/kick-assembler-acbg/blob/c912696a9fdfd5e70d5195ee128fecacd94bc391/src/main/resources/META-INF/plugin.xml)
