### ISSUE TITLE
Add SDK fails silently

### ISSUE THREAD

**Issue by christo** [4ch1m/kick-assembler-acbg#5]
Hi there, I have created a new issue since you already closed the previous one #4 even though the problem persists when I follow your suggestion.

With a fresh install of Intellij IDEA Ultimate downloaded today, after installing the latest kick assembler plugin from the "plugin marketplace", if I add SDK to my project (following the docs) and navigate to the directory where I have Kick Assembler installed, after clicking the "open" button on the file dialog, the result is that there is no SDK added or selected for the project, no message to say that something failed, no log entry in any log file I can find in the usual places. No nothing. The project configuration window looks exactly has it was before I chose to add an SDK.

Running on Mac OSX 10.15.5

**Comment by christo** [comment]
I did an additional test. When I choose a directory that is NOT the kick assembler install directory, the result of attempting the add a kick assembler SDK is that the expected error message shows:

```
Select Home Directory for Kick Assembler SDK

The selected directory is not a valid home for Kick Assembler SDK

```
So this path is not the one taken when I choose my true kick assembler directory. It seems clear that while this problem does not happen for everyone all the time, at the very least, error reporting and logging is insufficient to diagnose the problem.

**Comment by 4ch1m** [comment]
Hi @christo,

I just did yet another test with a standard installation of "IntelliJ Idea Community 2020.1" and "KickAssembler 5.16"... this time on Windows10.

Again... it works just fine.
The SDK gets detected and the version number automatically identified.

I don't think there's an issue with the implementation.

As previously mentioned, the responsible code-parts can be found here:

* [KickAssemblerSdk.java](https://github.com/4ch1m/kick-assembler-acbg/blob/master/src/main/java/de/achimonline/kickassembler/acbg/sdk/KickAssemblerSdk.java)
* [KickAssemblerSdkType.java](https://github.com/4ch1m/kick-assembler-acbg/blob/master/src/main/java/de/achimonline/kickassembler/acbg/sdk/KickAssemblerSdkType.java)

If you want to debug these classes/methods, simply check out the project and run the "runIde"-Gradle-Task in debug mode.

More indepth documentation about IntelliJIDEA-plugins and custom SDKs can be found here:

* https://www.jetbrains.org/intellij/sdk/docs/basics/getting_started.html
* https://www.jetbrains.org/intellij/sdk/docs/reference_guide/project_model/sdk.html

If you should find any bugs or have useful improvements to the SDK-handling, I'd be glad to receive a pull request from you.

Thanks!

**Comment by christo** [comment]
Hi @4ch1m as I hope you can see from my pull request, there was a problem in the implementation causing the behaviour I described. I hope you find the fix acceptable.
